# Generated by Django 2.0 on 2018-04-24 02:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_control', models.CharField(max_length=20)),
                ('source_control_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_name', models.CharField(max_length=25)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('environment_name',),
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.Environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('project_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.ProjectEnvironment')),
            ],
        ),
        migrations.CreateModel(
            name='SuiteRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tests', models.IntegerField(default=0)),
                ('passed_tests', models.IntegerField(default=0)),
                ('failed_tests', models.IntegerField(default=0)),
                ('inconclusive_tests', models.IntegerField(default=0)),
                ('ignored_tests', models.IntegerField(default=0)),
                ('result_precentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_execution_time', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.Suite')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('test_category', models.CharField(blank=True, max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('namespace', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('bugs', models.ManyToManyField(to='resoluteqa.Bug')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.Suite')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=20)),
                ('host', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('total_execution_time', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('console_output', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('suite_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.SuiteRun')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.Test')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='environments',
            field=models.ManyToManyField(through='resoluteqa.ProjectEnvironment', to='resoluteqa.Environment'),
        ),
        migrations.AddField(
            model_name='error',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.TestResult'),
        ),
    ]
