# Generated by Django 2.0 on 2018-02-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluteqa', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_control', models.CharField(max_length=20)),
                ('source_control_id', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
