# Generated by Django 2.0 on 2018-02-04 20:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resoluteqa', '0004_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=20)),
                ('host', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('total_execution_time', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('console_output', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('suite_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.SuiteRun')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.Test')),
            ],
        ),
    ]
