# Generated by Django 2.0 on 2018-02-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resoluteqa', '0006_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.Bug')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluteqa.Test')),
            ],
        ),
    ]
