# Generated by Django 2.0 on 2018-02-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resoluteqa', '0008_auto_20180208_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='description',
            new_name='title',
        ),
    ]
