# Generated by Django 2.0 on 2018-04-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluteqa', '0011_suiterun_result_precentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suiterun',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='suiterun',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
