# Generated by Django 2.0 on 2018-04-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluteqa', '0012_auto_20180408_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='bugs',
            field=models.ManyToManyField(through='resoluteqa.TestBug', to='resoluteqa.Bug'),
        ),
    ]
