# Generated by Django 2.0 on 2018-04-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluteqa', '0013_test_bugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbug',
            name='bug',
        ),
        migrations.RemoveField(
            model_name='testbug',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='bugs',
        ),
        migrations.AddField(
            model_name='test',
            name='bugs',
            field=models.ManyToManyField(to='resoluteqa.Bug'),
        ),
        migrations.DeleteModel(
            name='TestBug',
        ),
    ]
